project_id = "seniorityguru"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000/auth/confirm",
  "http://127.0.0.1:3000/auth/confirm",
  "http://localhost:3000/auth/update-password",
  "http://127.0.0.1:3000/auth/update-password",
  "http://localhost:3000/auth/accept-invite",
  "http://127.0.0.1:3000/auth/accept-invite",
  "https://seniorityguru.com/auth/confirm",
  "https://seniorityguru.com/auth/update-password",
  "https://seniorityguru.com/auth/accept-invite"
]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
otp_length = 6

[auth.email.template.invite]
subject = "You're invited to SeniorityGuru"
content_path = "./supabase/templates/invite.html"

[auth.email.template.confirmation]
subject = "Confirm your email"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset your password"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.email_change]
subject = "Confirm your email change"
content_path = "./supabase/templates/email_change.html"
