// @vitest-environment node
import { describe, it, expect } from 'vitest'
import { genericParser, findHeaderRow, countNonEmpty, extractMetadata } from './generic'

describe('genericParser', () => {
  it('has correct id and label', () => {
    expect(genericParser.id).toBe('generic')
    expect(genericParser.label).toBe('Generic / Other Airline')
  })

  it('passes through clean data (no preamble) unchanged', () => {
    const raw = [
      ['Seniority Number', 'Employee Number', 'Seat', 'Base', 'Fleet', 'Hire Date', 'Retire Date'],
      ['1', '900001', 'CA', 'ATL', '737', '2010-01-15', '2045-06-01'],
      ['2', '900002', 'FO', 'JFK', '320', '2015-03-20', '2050-09-15'],
    ]
    const result = genericParser.parse(raw)
    expect(result.rows).toEqual(raw)
  })

  it('returns null metadata when no preamble', () => {
    const raw = [
      ['Seniority Number', 'Employee Number', 'Seat', 'Base', 'Fleet', 'Hire Date', 'Retire Date'],
      ['1', '900001', 'CA', 'ATL', '737', '2010-01-15', '2045-06-01'],
    ]
    const result = genericParser.parse(raw)
    expect(result.metadata).toEqual({ effectiveDate: null, title: null })
  })

  it('skips blank rows before header', () => {
    const raw = [
      ['', '', '', '', '', '', ''],
      ['', '', '', '', '', '', ''],
      ['Seniority Number', 'Employee Number', 'Seat', 'Base', 'Fleet', 'Hire Date', 'Retire Date'],
      ['1', '900001', 'CA', 'ATL', '737', '2010-01-15', '2045-06-01'],
    ]
    const result = genericParser.parse(raw)
    expect(result.rows[0]).toEqual(['Seniority Number', 'Employee Number', 'Seat', 'Base', 'Fleet', 'Hire Date', 'Retire Date'])
    expect(result.rows).toHaveLength(2)
  })

  it('skips title rows with 1-2 non-empty cells', () => {
    const raw = [
      ['Seniority List March 2026', '', '', '', '', '', ''],
      ['Generated by HR System', '', '', '', '', '', ''],
      ['Seniority Number', 'Employee Number', 'Seat', 'Base', 'Fleet', 'Hire Date', 'Retire Date'],
      ['1', '900001', 'CA', 'ATL', '737', '2010-01-15', '2045-06-01'],
    ]
    const result = genericParser.parse(raw)
    expect(result.rows[0]).toEqual(['Seniority Number', 'Employee Number', 'Seat', 'Base', 'Fleet', 'Hire Date', 'Retire Date'])
    expect(result.rows).toHaveLength(2)
  })

  it('extracts effective date from preamble', () => {
    const raw = [
      ['Seniority List 01Mar2026', '', '', '', '', '', ''],
      ['', '', '', '', '', '', ''],
      ['Seniority Number', 'Employee Number', 'Seat', 'Base', 'Fleet', 'Hire Date', 'Retire Date'],
      ['1', '900001', 'CA', 'ATL', '737', '2010-01-15', '2045-06-01'],
    ]
    const result = genericParser.parse(raw)
    expect(result.metadata.effectiveDate).toBe('2026-03-01')
    expect(result.metadata.title).toBe('Seniority List 01Mar2026')
  })

  it('falls back to row 0 when no row has 5+ non-empty cells', () => {
    const raw = [
      ['Col A', 'Col B'],
      ['val1', 'val2'],
    ]
    const result = genericParser.parse(raw)
    expect(result.rows).toEqual(raw)
  })
})

describe('findHeaderRow', () => {
  it('returns index of first row with 5+ non-empty cells', () => {
    const rows = [
      ['Title', '', '', '', '', '', ''],
      ['', '', '', '', '', '', ''],
      ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
    ]
    expect(findHeaderRow(rows)).toBe(2)
  })

  it('returns 0 when no row has 5+ non-empty cells', () => {
    const rows = [
      ['A', 'B'],
      ['C', 'D'],
    ]
    expect(findHeaderRow(rows)).toBe(0)
  })
})

describe('countNonEmpty', () => {
  it('counts non-empty cells in a row', () => {
    expect(countNonEmpty(['a', '', 'b', '  ', 'c'])).toBe(3)
  })

  it('returns 0 for all-empty row', () => {
    expect(countNonEmpty(['', '', '  ', ''])).toBe(0)
  })
})

describe('extractMetadata', () => {
  it('extracts date from preamble text like "Seniority List 01Mar2026"', () => {
    const preamble = [['Seniority List 01Mar2026', '', '']]
    const result = extractMetadata(preamble)
    expect(result.effectiveDate).toBe('2026-03-01')
    expect(result.title).toBe('Seniority List 01Mar2026')
  })

  it('extracts date from various formats', () => {
    const preamble = [['Published 03/15/2026', '', '']]
    const result = extractMetadata(preamble)
    expect(result.effectiveDate).toBe('2026-03-15')
  })

  it('returns null when no date found in preamble', () => {
    const preamble = [['Some Random Title', '', '']]
    const result = extractMetadata(preamble)
    expect(result.effectiveDate).toBeNull()
    expect(result.title).toBeNull()
  })
})
